CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER NOT NULL,
  "username" VARCHAR(32) NOT NULL,
  "password" VARCHAR(256) NOT NULL,
  PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "links" (
  "id" INTEGER NOT NULL,
  "user_id" INTEGER,
  "url" VARCHAR(256),
  "short" VARCHAR(16) UNIQUE,
  "visits" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY("id" AUTOINCREMENT)
);